apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://localhost:9411/api/v2/spans"
  metric:
    enabled: true
  mtls:
    enabled: false
  middleware:
    http:
      - name: oauth2
        type: middleware.http.oauth2
  accessControl:
    defaultAction: allow
    trustDomain: "localhost"